### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by hansmrtn** [moonshotcollective/pay.party#15]
Milestone Goals for: Oct 4th - Oct 18, 2021

- [x] README of Dev Branch 
- [ ] Code Guidelines
- [x] Chakra UI
- [x] Hashed Elections Data model 
- [x] Ceramic Handler
- [x] Strategies Handler 
- [x] CI/CD Backend
